### ISSUE TITLE
GUI with NBT

### ISSUE THREAD

**Issue by Eufranio** [caoli5288/xKit#4]
Would be nice if you add a option to the players see a GUI that the owners configure, to show the kits content.

**Comment by caoli5288** [comment]
You mean a item in configured slot?

**Comment by Eufranio** [comment]
Kinda, I have some kits set. I wanted to know if you could make a GUI to show some contents, like:

/xkit creategui <name>
The GUI will be created, and the admin will use 
/xkit editgui <name>
to drag and drop items in the GUI (items with NBT data, because most of the GUI plugins doesn't support NBT) similar to the kit GUI
Players will be able to run
/xkit opengui <name> to see the GUI

I would use it in my server to show the content of the kits

**Comment by caoli5288** [comment]
I think it's not necessary. You can show it in website with more flexibility. :-)

**Comment by Eufranio** [comment]
The items that contais NBT mostly has tooltips with energy, contents, etc... But i would like if it be implemented by you :/

**Comment by caoli5288** [comment]
Feel sorry I don't think it's necessary. Close issue.

Regards.
